<?= $this->fetch('_head.phtml') ?>
    <h1>Users from Ustka</h1>
    <div>a microframework for PHP</div>

    <table>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?= $user['name']; ?></td>
                <td><?= $user['lastname']; ?></td>
                <td><?= $user['city']; ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?= $this->fetch('_footer.phtml') ?>